#> left_click_detection:core/load
#
# load時に実行される
#
# @within tag/function minecraft:load

#> team設定
# @within left_click_detection:**
# vc-archived: archive notice (generated by the archive-gates patch)
say [LeftClickDetection] ARCHIVED datapack (vortacraftmc/core, 2026-10-03): unmaintained, deploy not recommended. It runs commands at server permission level and can lag, crash or alter your world - review the code and back up first. See ARCHIVED.md in the pack folder.
team add LeftClickDetection
team modify LeftClickDetection collisionRule never
