# macroengine:gate/v26_4/load - load gate for macroEngine v26.4-snapshot-1 (generated by the archive-gates patch)
# Returns 1 = pack may initialise, 0 = pack stays inert. Never blocks server startup.
# Gates: 0 archive notice | 1 version/format (+ variant conflict) | 2 operator confirm
#        3 lockdown | 4 reload breaker | 5 sink guard (inline in the macro-sink functions)

# Gate 0: archive notice (console + chat)
say [macroEngine] ARCHIVED datapack (vortacraftmc/core, 2026-10-03): unmaintained, deploy not recommended. Runs commands at server permission level and can lag, crash or alter your world - review the code and back up first.
say [macroEngine] See ARCHIVED.md in the pack folder.

scoreboard objectives add macroengine.gate dummy
execute unless data storage macroengine:gate/v26_4 state run data modify storage macroengine:gate/v26_4 state set value "pending"

# Gate 2: confirmation is bound to the pack version; a different version re-arms it.
# A locked pack stays locked until unlock.
execute unless data storage macroengine:gate/v26_4 {confirmed:"v26.4-snapshot-1"} run data modify storage macroengine:gate/v26_4 state set value "pending"
execute if data storage macroengine:gate/v26_4 {confirmed:"v26.4-snapshot-1"} unless data storage macroengine:gate/v26_4 {state:"locked"} run data modify storage macroengine:gate/v26_4 state set value "active"

# Gate 4: reload breaker. More than 5 loads with gaps of 200 ticks or less -> lock.
scoreboard players add #last macroengine.gate 0
scoreboard players add #n macroengine.gate 0
execute store result score #now macroengine.gate run time query gametime
scoreboard players operation #dt macroengine.gate = #now macroengine.gate
scoreboard players operation #dt macroengine.gate -= #last macroengine.gate
execute if score #dt macroengine.gate matches 0..200 run scoreboard players add #n macroengine.gate 1
execute unless score #dt macroengine.gate matches 0..200 run scoreboard players set #n macroengine.gate 1
scoreboard players operation #last macroengine.gate = #now macroengine.gate
execute if score #n macroengine.gate matches 6.. run data modify storage macroengine:gate/v26_4 state set value "locked"
execute if score #n macroengine.gate matches 6.. run data modify storage macroengine:gate/v26_4 reason set value "reload breaker: more than 5 loads within 200 ticks of each other"

# Result
execute if data storage macroengine:gate/v26_4 {state:"active"} run return 1
execute if data storage macroengine:gate/v26_4 {state:"locked"} run say [macroEngine] LOCKED. Reason is in storage macroengine:gate/v26_4 (reason). Operator: tag yourself macroengine.gate_admin, then run /function macroengine:gate/v26_4/unlock
execute if data storage macroengine:gate/v26_4 {state:"pending"} run say [macroEngine] PENDING operator confirmation - the pack is inert. 1) /tag <you> add macroengine.gate_admin  2) /function macroengine:gate/v26_4/confirm {format:122}
execute if data storage macroengine:gate/v26_4 {state:"pending"} run say [macroEngine] format = data pack version of your server (pack_version.data in its version.json); this build targets 122.
return fail
