# ==============================================================================
# vortacraftmc/core - Provenance Watermark
#
# File: _vc_origin.mcfunction
# watermark-version: 2
# pack:      RTWrapper-v1.0.1
# namespace: rtwrapper
# source:    packs/RTWrapper-v1.0.1
#
# Description:
#   This file serves as a permanent origin watermark for this datapack within
#   the vortacraftmc/core monorepo repository.
#
#   Original source: Runtoolkit (runtoolkit/suite, now archived; the
#   organization was retired in favor of vortacraftmc). This project is derived
#   from Runtoolkit's work; the original copyright notice is retained below.
#
# Build Workflow Rules:
#   1. MUST remain permanently under data/<namespace>/function/ in the source
#      tree (packs/). Removing or editing this file manually will cause the
#      "checkOriginWatermarks" and "zipPacks" Gradle tasks to fail.
#   2. During the release packaging process ("gradle zipPacks"), this file is
#      automatically stripped from the temporary "build/packs-remap/" working
#      copy, ensuring distribution ZIP files remain clean.
#   3. Content is generated by scripts/origin_watermarks.py (run with --write);
#      the same script (--check) verifies it in CI. Do not edit by hand.
#
# Copyright (c) 2026 Runtoolkit. Covered under the project's MIT License.
# ==============================================================================

# No-op marker function executed when invoked directly.
# Do not edit this file directly.
