# DailyBonus - runs once on datapack (re)load
# vc-archived: archive notice (generated by the archive-gates patch)
say [DailyBonus] ARCHIVED datapack (vortacraftmc/core, 2026-10-03): unmaintained, deploy not recommended. It runs commands at server permission level and can lag, crash or alter your world - review the code and back up first. See ARCHIVED.md in the pack folder.
scoreboard objectives add db_last_day dummy
scoreboard objectives add db_gameday dummy
scoreboard players set #const24000 db_gameday 24000
tellraw @a {"text":"[DailyBonus] loaded.","color":"gray"}
