# macroengine:core/internal/pev/block/anvil (generated by tools/gen_block_events.py)
# Reward of the anvil advancement. @s = the player who used the block.
advancement revoke @s only macroengine:core/internal/pev/block/anvil
function #macroengine:core/internal/pev/block/anvil
