# macroengine:core/internal/pev/block/beacon (generated by tools/gen_block_events.py)
# Reward of the beacon advancement. @s = the player who used the block.
advancement revoke @s only macroengine:core/internal/pev/block/beacon
function #macroengine:core/internal/pev/block/beacon
