# macroengine:core/internal/pev/block/blast_furnace (generated by tools/gen_block_events.py)
# Reward of the blast_furnace advancement. @s = the player who used the block.
advancement revoke @s only macroengine:core/internal/pev/block/blast_furnace
function #macroengine:core/internal/pev/block/blast_furnace
