# macroengine:core/internal/pev/block/brewing_stand (generated by tools/gen_block_events.py)
# Reward of the brewing_stand advancement. @s = the player who used the block.
advancement revoke @s only macroengine:core/internal/pev/block/brewing_stand
function #macroengine:core/internal/pev/block/brewing_stand
