# macroengine:core/internal/pev/block/campfire (generated by tools/gen_block_events.py)
# Reward of the campfire advancement. @s = the player who used the block.
advancement revoke @s only macroengine:core/internal/pev/block/campfire
function #macroengine:core/internal/pev/block/campfire
