# macroengine:core/internal/pev/block/cartography_table (generated by tools/gen_block_events.py)
# Reward of the cartography_table advancement. @s = the player who used the block.
advancement revoke @s only macroengine:core/internal/pev/block/cartography_table
function #macroengine:core/internal/pev/block/cartography_table
