# macroengine:core/internal/pev/block/cauldron (generated by tools/gen_block_events.py)
# Reward of the cauldron advancement. @s = the player who used the block.
advancement revoke @s only macroengine:core/internal/pev/block/cauldron
function #macroengine:core/internal/pev/block/cauldron
