# macroengine:core/internal/pev/block/chest (generated by tools/gen_block_events.py)
# Reward of the chest advancement. @s = the player who used the block.
advancement revoke @s only macroengine:core/internal/pev/block/chest
function #macroengine:core/internal/pev/block/chest
