# macroengine:core/internal/pev/block/dispenser (generated by tools/gen_block_events.py)
# Reward of the dispenser advancement. @s = the player who used the block.
advancement revoke @s only macroengine:core/internal/pev/block/dispenser
function #macroengine:core/internal/pev/block/dispenser
