# macroengine:core/internal/pev/block/ender_chest (generated by tools/gen_block_events.py)
# Reward of the ender_chest advancement. @s = the player who used the block.
advancement revoke @s only macroengine:core/internal/pev/block/ender_chest
function #macroengine:core/internal/pev/block/ender_chest
