# macroengine:core/internal/pev/block/flower_pot (generated by tools/gen_block_events.py)
# Reward of the flower_pot advancement. @s = the player who used the block.
advancement revoke @s only macroengine:core/internal/pev/block/flower_pot
function #macroengine:core/internal/pev/block/flower_pot
