# macroengine:core/internal/pev/block/furnace (generated by tools/gen_block_events.py)
# Reward of the furnace advancement. @s = the player who used the block.
advancement revoke @s only macroengine:core/internal/pev/block/furnace
function #macroengine:core/internal/pev/block/furnace
