# macroengine:core/internal/pev/block/grindstone (generated by tools/gen_block_events.py)
# Reward of the grindstone advancement. @s = the player who used the block.
advancement revoke @s only macroengine:core/internal/pev/block/grindstone
function #macroengine:core/internal/pev/block/grindstone
