# macroengine:core/internal/pev/block/hopper (generated by tools/gen_block_events.py)
# Reward of the hopper advancement. @s = the player who used the block.
advancement revoke @s only macroengine:core/internal/pev/block/hopper
function #macroengine:core/internal/pev/block/hopper
