# macroengine:core/internal/pev/block/jukebox (generated by tools/gen_block_events.py)
# Reward of the jukebox advancement. @s = the player who used the block.
advancement revoke @s only macroengine:core/internal/pev/block/jukebox
function #macroengine:core/internal/pev/block/jukebox
