# macroengine:core/internal/pev/block/lectern (generated by tools/gen_block_events.py)
# Reward of the lectern advancement. @s = the player who used the block.
advancement revoke @s only macroengine:core/internal/pev/block/lectern
function #macroengine:core/internal/pev/block/lectern
