# macroengine:core/internal/pev/block/note_block (generated by tools/gen_block_events.py)
# Reward of the note_block advancement. @s = the player who used the block.
advancement revoke @s only macroengine:core/internal/pev/block/note_block
function #macroengine:core/internal/pev/block/note_block
