# macroengine:core/internal/pev/block/shulker_box (generated by tools/gen_block_events.py)
# Reward of the shulker_box advancement. @s = the player who used the block.
advancement revoke @s only macroengine:core/internal/pev/block/shulker_box
function #macroengine:core/internal/pev/block/shulker_box
