# macroengine:core/internal/pev/block/smoker (generated by tools/gen_block_events.py)
# Reward of the smoker advancement. @s = the player who used the block.
advancement revoke @s only macroengine:core/internal/pev/block/smoker
function #macroengine:core/internal/pev/block/smoker
