# macroengine:core/internal/pev/block/stonecutter (generated by tools/gen_block_events.py)
# Reward of the stonecutter advancement. @s = the player who used the block.
advancement revoke @s only macroengine:core/internal/pev/block/stonecutter
function #macroengine:core/internal/pev/block/stonecutter
