# macroengine:core/internal/pev/block/trapped_chest (generated by tools/gen_block_events.py)
# Reward of the trapped_chest advancement. @s = the player who used the block.
advancement revoke @s only macroengine:core/internal/pev/block/trapped_chest
function #macroengine:core/internal/pev/block/trapped_chest
