blank_issues_enabled: false
contact_links:
  - name: Questions & Discussion
    url: https://github.com/vortacraftmc/core/discussions
    about: Please use Discussions for general questions and conversation.
