# rtwrapper:gate/r1_21_1/load - load gate for RTWrapper v1.0.0 (generated by the archive-gates patch)
# Returns 1 = pack may initialise, 0 = pack stays inert. Never blocks server startup.
# Gates: 0 archive notice | 1 version/format (+ variant conflict) | 2 operator confirm
#        3 lockdown | 4 reload breaker | 5 sink guard (inline in the macro-sink functions)

# Gate 0: archive notice (console + chat)
say [RTWrapper] ARCHIVED datapack (vortacraftmc/core, 2026-10-03): unmaintained, deploy not recommended. It runs commands at server permission level and can lag, crash or alter your world - review the code and back up first. See ARCHIVED.md in the pack folder.

scoreboard objectives add rtwrapper.gate dummy
execute unless data storage rtwrapper:gate/r1_21_1 state run data modify storage rtwrapper:gate/r1_21_1 state set value "pending"

# Gate 1b: variant conflict. Two RTWrapper builds share the rtwrapper namespace; if another
# variant ran its gate in this same tick, lock both.
execute store result score #seen.r1_21_1 rtwrapper.gate run time query gametime
execute if score #seen.v1_0_1 rtwrapper.gate = #seen.r1_21_1 rtwrapper.gate run data modify storage rtwrapper:gate/r1_21_1 state set value "locked"
execute if score #seen.v1_0_1 rtwrapper.gate = #seen.r1_21_1 rtwrapper.gate run data modify storage rtwrapper:gate/r1_21_1 reason set value "variant conflict: v1_0_1 loaded in the same tick"
execute if score #seen.v1_0_1 rtwrapper.gate = #seen.r1_21_1 rtwrapper.gate run data modify storage rtwrapper:gate/v1_0_1 state set value "locked"
execute if score #seen.v1_0_1 rtwrapper.gate = #seen.r1_21_1 rtwrapper.gate run data modify storage rtwrapper:gate/v1_0_1 reason set value "variant conflict: r1_21_1 loaded in the same tick"
execute if score #seen.r26_3 rtwrapper.gate = #seen.r1_21_1 rtwrapper.gate run data modify storage rtwrapper:gate/r1_21_1 state set value "locked"
execute if score #seen.r26_3 rtwrapper.gate = #seen.r1_21_1 rtwrapper.gate run data modify storage rtwrapper:gate/r1_21_1 reason set value "variant conflict: r26_3 loaded in the same tick"
execute if score #seen.r26_3 rtwrapper.gate = #seen.r1_21_1 rtwrapper.gate run data modify storage rtwrapper:gate/r26_3 state set value "locked"
execute if score #seen.r26_3 rtwrapper.gate = #seen.r1_21_1 rtwrapper.gate run data modify storage rtwrapper:gate/r26_3 reason set value "variant conflict: r1_21_1 loaded in the same tick"

# Gate 2: confirmation is bound to the pack version; a different version re-arms it.
# A locked pack stays locked until unlock.
execute unless data storage rtwrapper:gate/r1_21_1 {confirmed:"v1.0.0"} run data modify storage rtwrapper:gate/r1_21_1 state set value "pending"
execute if data storage rtwrapper:gate/r1_21_1 {confirmed:"v1.0.0"} unless data storage rtwrapper:gate/r1_21_1 {state:"locked"} run data modify storage rtwrapper:gate/r1_21_1 state set value "active"

# Gate 4: reload breaker. More than 5 loads with gaps of 200 ticks or less -> lock.
scoreboard players add #last rtwrapper.gate 0
scoreboard players add #n rtwrapper.gate 0
execute store result score #now rtwrapper.gate run time query gametime
scoreboard players operation #dt rtwrapper.gate = #now rtwrapper.gate
scoreboard players operation #dt rtwrapper.gate -= #last rtwrapper.gate
execute if score #dt rtwrapper.gate matches 0..200 run scoreboard players add #n rtwrapper.gate 1
execute unless score #dt rtwrapper.gate matches 0..200 run scoreboard players set #n rtwrapper.gate 1
scoreboard players operation #last rtwrapper.gate = #now rtwrapper.gate
execute if score #n rtwrapper.gate matches 6.. run data modify storage rtwrapper:gate/r1_21_1 state set value "locked"
execute if score #n rtwrapper.gate matches 6.. run data modify storage rtwrapper:gate/r1_21_1 reason set value "reload breaker: more than 5 loads within 200 ticks of each other"

# Result
execute if data storage rtwrapper:gate/r1_21_1 {state:"active"} run return 1
execute if data storage rtwrapper:gate/r1_21_1 {state:"locked"} run say [RTWrapper] LOCKED. Reason is in storage rtwrapper:gate/r1_21_1 (reason). Operator: tag yourself rtwrapper.gate_admin, then run /function rtwrapper:gate/r1_21_1/unlock
execute if data storage rtwrapper:gate/r1_21_1 {state:"pending"} run say [RTWrapper] PENDING operator confirmation - the pack is inert. 1) /tag <you> add rtwrapper.gate_admin  2) /function rtwrapper:gate/r1_21_1/confirm {format:48}  (format = data pack version of your server, pack_version.data in its version.json; this build targets 48)
return fail
