#!/usr/bin/env python3
"""Generate, verify and report the provenance watermarks (_vc_origin.mcfunction).

Every datapack under packs/ carries data/<namespace>/function/_vc_origin.mcfunction.
build.gradle (checkOriginWatermarks / zipPacks) only proves such a file EXISTS in
the right folder. This tool owns the CONTENT:

  * one template generates every watermark, so the 20 copies cannot drift apart
  * each file records machine-readable fields (pack, namespace, source) that are
    checked against where the file actually lives
  * a watermark must stay a no-op: only comments and blank lines are accepted, so
    nothing executable can be hidden in a file that reviewers are told to skip

Usage (from anywhere inside the repo):
  python3 scripts/origin_watermarks.py            check (default), exit 1 on problems
  python3 scripts/origin_watermarks.py --report   table of every pack and watermark
  python3 scripts/origin_watermarks.py --json     same report as JSON
  python3 scripts/origin_watermarks.py --write    (re)generate watermarks; creates one
                                                  for a pack that has none

Maintainers run --write; contributors do not hand-edit these files (CONTRIBUTING.md).
Resource packs (assets/ without data/) carry no watermark, same as build.gradle.
"""
import argparse
import json
import os
import signal
import sys

NAME = "_vc_origin.mcfunction"
WATERMARK_VERSION = 2
SKIP_DIRS = {".git", "build", ".gradle", "node_modules"}

# The prose below is the project's existing provenance/copyright wording. It is
# kept verbatim (one place instead of 20); changing it is a legal decision for
# the maintainers, not something this tool decides.
TEMPLATE = """\
# ==============================================================================
# vortacraftmc/core - Provenance Watermark
#
# File: _vc_origin.mcfunction
# watermark-version: {version}
# pack:      {pack}
# namespace: {namespace}
# source:    {source}
#
# Description:
#   This file serves as a permanent origin watermark for this datapack within
#   the vortacraftmc/core monorepo repository.
#
#   Original source: Runtoolkit (runtoolkit/suite, now archived; the
#   organization was retired in favor of vortacraftmc). This project is derived
#   from Runtoolkit's work; the original copyright notice is retained below.
#
# Build Workflow Rules:
#   1. MUST remain permanently under data/<namespace>/function/ in the source
#      tree (packs/). Removing or editing this file manually will cause the
#      "checkOriginWatermarks" and "zipPacks" Gradle tasks to fail.
#   2. During the release packaging process ("gradle zipPacks"), this file is
#      automatically stripped from the temporary "build/packs-remap/" working
#      copy, ensuring distribution ZIP files remain clean.
#   3. Content is generated by scripts/origin_watermarks.py (run with --write);
#      the same script (--check) verifies it in CI. Do not edit by hand.
#
# Copyright (c) 2026 Runtoolkit. Covered under the project's MIT License.
# ==============================================================================

# No-op marker function executed when invoked directly.
# Do not edit this file directly.
"""


def repo_root():
    here = os.path.abspath(os.path.dirname(__file__))
    cur = here
    while True:
        if os.path.isdir(os.path.join(cur, "packs")) and os.path.exists(os.path.join(cur, "build.gradle")):
            return cur
        parent = os.path.dirname(cur)
        if parent == cur:
            sys.exit("origin_watermarks: cannot find the repository root (packs/ + build.gradle)")
        cur = parent


ROOT = repo_root()


def read_text(path):
    with open(path, encoding="utf-8") as fh:
        return fh.read()


def rel(path):
    return os.path.relpath(path, ROOT).replace(os.sep, "/")


def find_pack_dirs():
    """Directories holding a pack.mcmeta under packs/, like build.gradle's findPackDirs."""
    found = []
    for base, dirs, files in os.walk(os.path.join(ROOT, "packs")):
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
        if "pack.mcmeta" in files:
            found.append(base)
    return sorted(found)


def is_resource_pack(pack_dir):
    return os.path.isdir(os.path.join(pack_dir, "assets")) and not os.path.isdir(os.path.join(pack_dir, "data"))


def function_dir_name(ns_dir):
    # pack_format < 48 used 'functions'; newer packs use 'function'
    for name in ("function", "functions"):
        if os.path.isdir(os.path.join(ns_dir, name)):
            return name
    return None


def watermarks_of(pack_dir):
    """[(namespace, function-dir-name, path)] for every watermark already in the pack."""
    out = []
    data = os.path.join(pack_dir, "data")
    if not os.path.isdir(data):
        return out
    for ns in sorted(os.listdir(data)):
        ns_dir = os.path.join(data, ns)
        for fname in ("function", "functions"):
            p = os.path.join(ns_dir, fname, NAME)
            if os.path.isfile(p):
                out.append((ns, fname, p))
    return out


def primary_namespace(pack_dir):
    """Namespace that should carry a new watermark: the non-'minecraft' one with most files."""
    data = os.path.join(pack_dir, "data")
    best, best_n = None, -1
    for ns in sorted(os.listdir(data)):
        ns_dir = os.path.join(data, ns)
        fdir = function_dir_name(ns_dir) if os.path.isdir(ns_dir) else None
        if not fdir or ns == "minecraft":
            continue
        n = sum(len(f) for _, _, f in os.walk(os.path.join(ns_dir, fdir)))
        if n > best_n:
            best, best_n = (ns, fdir), n
    return best


def render(pack_dir, namespace):
    return TEMPLATE.format(
        version=WATERMARK_VERSION,
        pack=os.path.basename(pack_dir),
        namespace=namespace,
        source=rel(pack_dir),
    )


def non_comment_lines(text):
    return [(i, l) for i, l in enumerate(text.splitlines(), 1) if l.strip() and not l.lstrip().startswith("#")]


def check_file(pack_dir, ns, path):
    problems = []
    text = read_text(path)
    bad = non_comment_lines(text)
    if bad:
        i, l = bad[0]
        problems.append(f"{rel(path)}:{i}: executable line in a watermark, which must be comments only: {l.strip()[:60]}")
    if f"# namespace: {ns}\n" not in text:
        problems.append(f"{rel(path)}: 'namespace' field is missing or does not match the folder ({ns})")
    if f"# pack:      {os.path.basename(pack_dir)}\n" not in text:
        problems.append(f"{rel(path)}: 'pack' field is missing or does not match the pack folder")
    if f"# source:    {rel(pack_dir)}\n" not in text:
        problems.append(f"{rel(path)}: 'source' field is missing or does not match the pack path")
    if not problems and text != render(pack_dir, ns):
        problems.append(f"{rel(path)}: differs from the generated watermark (hand-edited or outdated template); run --write")
    return problems


def collect():
    packs = []
    for pack_dir in find_pack_dirs():
        resource = is_resource_pack(pack_dir)
        packs.append({
            "pack": os.path.basename(pack_dir),
            "source": rel(pack_dir),
            "resource_pack": resource,
            "watermarks": [] if resource else watermarks_of(pack_dir),
            "dir": pack_dir,
        })
    return packs


def do_check(packs):
    problems = []
    for p in packs:
        if p["resource_pack"]:
            continue
        if not p["watermarks"]:
            problems.append(f"{p['source']}: no watermark under data/<namespace>/function/ (run --write)")
        for ns, _f, path in p["watermarks"]:
            problems.extend(check_file(p["dir"], ns, path))
    return problems


def do_write(packs):
    changed = 0
    for p in packs:
        if p["resource_pack"]:
            continue
        targets = [(ns, path) for ns, _f, path in p["watermarks"]]
        if not targets:
            prim = primary_namespace(p["dir"])
            if prim is None:
                print(f"skip   {p['source']}: no namespace with a function folder")
                continue
            ns, fdir = prim
            targets = [(ns, os.path.join(p["dir"], "data", ns, fdir, NAME))]
        for ns, path in targets:
            new = render(p["dir"], ns)
            old = read_text(path) if os.path.exists(path) else None
            if old != new:
                with open(path, "w", encoding="utf-8", newline="\n") as fh:
                    fh.write(new)
                print(("create " if old is None else "update ") + rel(path))
                changed += 1
    print(f"{changed} watermark file(s) written")
    return changed


def do_report(packs, as_json):
    rows = []
    for p in packs:
        if p["resource_pack"]:
            rows.append({"pack": p["pack"], "source": p["source"], "kind": "resource pack", "namespaces": []})
        else:
            rows.append({"pack": p["pack"], "source": p["source"], "kind": "datapack",
                         "namespaces": [ns for ns, _f, _p in p["watermarks"]]})
    if as_json:
        print(json.dumps(rows, indent=2))
        return
    w = max(len(r["source"]) for r in rows)
    print(f"{'PACK PATH'.ljust(w)}  KIND           WATERMARK NAMESPACES")
    for r in rows:
        ns = ", ".join(r["namespaces"]) if r["namespaces"] else ("-" if r["kind"] == "resource pack" else "MISSING")
        print(f"{r['source'].ljust(w)}  {r['kind'].ljust(13)}  {ns}")
    dp = [r for r in rows if r["kind"] == "datapack"]
    print(f"\n{len(dp)} datapack(s), {sum(len(r['namespaces']) for r in dp)} watermark file(s), "
          f"{len(rows) - len(dp)} resource pack(s) without one")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    g = ap.add_mutually_exclusive_group()
    g.add_argument("--check", action="store_true", help="verify every watermark (default)")
    g.add_argument("--write", action="store_true", help="generate or update watermarks")
    g.add_argument("--report", action="store_true", help="print a table of packs and watermarks")
    g.add_argument("--json", action="store_true", help="print the report as JSON")
    a = ap.parse_args()

    packs = collect()
    if a.write:
        do_write(packs)
        return 0
    if a.report or a.json:
        do_report(packs, a.json)
        return 0
    problems = do_check(packs)
    for pr in problems:
        print("ERROR  " + pr)
    n = sum(len(p["watermarks"]) for p in packs)
    if problems:
        print(f"\norigin_watermarks: {len(problems)} problem(s) in {n} watermark file(s)")
        return 1
    print(f"origin_watermarks: ok ({n} watermark file(s) in {sum(1 for p in packs if not p['resource_pack'])} datapack(s))")
    return 0


if __name__ == "__main__":
    if hasattr(signal, "SIGPIPE"):
        signal.signal(signal.SIGPIPE, signal.SIG_DFL)  # `| head` must not traceback
    sys.exit(main())
