"""Datapack file generators."""

from __future__ import annotations

from typing import Any

from ..security import assert_generated_paths_safe, assert_generated_size_limits
from .fill import generate_fill_router, generate_page_fills
from .handlers import generate_handlers
from .lifecycle import (
    generate_close,
    generate_load,
    generate_open,
    generate_pack_mcmeta,
    generate_tags,
)
from .tick import generate_tick


def generate_datapack(menu: dict[str, Any]) -> dict[str, str]:
    """Generate all datapack files. Returns path → content map."""
    out: dict[str, str] = {}
    generate_load(menu, out)
    generate_open(menu, out)
    generate_close(menu, out)
    generate_fill_router(menu, out)
    generate_page_fills(menu, out)
    generate_handlers(menu, out)
    generate_tick(menu, out)
    generate_tags(menu, out)
    desc = menu.get("pack_description") or f"{menu['display_name']} (generated by guigenmc)"
    generate_pack_mcmeta(out, desc)
    assert_generated_paths_safe(out)
    assert_generated_size_limits(out)
    return out


def summarize(menu: dict[str, Any]) -> dict[str, Any]:
    from ..models import all_widgets, container_slot_count, menu_function_prefix

    return {
        "namespace": menu["namespace"],
        "menu_id": menu["menu_id"],
        "pages": len(menu["pages"]),
        "widgets": len(all_widgets(menu)),
        "container": f"{menu['container']['type']} ({container_slot_count(menu['container'])} slots)",
        "open_command": f"/function {menu_function_prefix(menu)}/open",
    }
