# ==============================================================================
# vortacraftmc/core - Provenance Watermark
#
# File: _vc_origin.mcfunction
#
# Description:
#   This file serves as a permanent origin watermark for this datapack within
#   the vortacraftmc/core monorepo repository.
#
#   Original source: Runtoolkit (runtoolkit/suite). This project is derived
#   from Runtoolkit's work; the original copyright notice is retained below.
#
# Build Workflow Rules:
#   1. MUST remain permanently under data/<namespace>/function/ in the source
#      tree (packs/). Removing or editing this file manually will cause the
#      "checkOriginWatermarks" and "zipPacks" Gradle tasks to fail.
#   2. During the release packaging process ("gradle zipPacks"), this file is
#      automatically stripped from the temporary "build/packs-remap/" working
#      copy, ensuring distribution ZIP files remain clean.
#
# Copyright (c) 2026 Runtoolkit. Covered under the project's MIT License.
# ==============================================================================

# No-op marker function executed when invoked directly.
# Do not edit this file directly.
