#!/usr/bin/env python3
"""Generates the block-interaction events of macroEngine's player-event module.

One row of TABLE produces, under data/macroengine/:
  advancement/core/internal/pev/block/<name>.json     (the vanilla trigger)
  function/core/internal/pev/block/<name>.mcfunction  (re-arms it, fires the tag)
  tags/function/core/internal/pev/block/<name>.json   (per-block extension point)
and the shared group tags block_use / open_gui.

Usage (from the pack root):  python3 tools/gen_block_events.py
Re-running rewrites every generated file, so edit TABLE, never the output.
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent / "data" / "macroengine"
NS = "macroengine:core/internal/pev"

DEFAULT_USE = "minecraft:default_block_use"      # block handled the right click itself
ITEM_USE = "minecraft:item_used_on_block"        # an item was used on the block

# name, trigger, blocks (list of ids, or one '#tag'), opens a GUI
TABLE = [
    ("anvil",            DEFAULT_USE, ["minecraft:anvil"],                  True),
    ("barrel",           DEFAULT_USE, ["minecraft:barrel"],                 True),
    ("beacon",           DEFAULT_USE, ["minecraft:beacon"],                 True),
    ("blast_furnace",    DEFAULT_USE, ["minecraft:blast_furnace"],          True),
    ("brewing_stand",    DEFAULT_USE, ["minecraft:brewing_stand"],          True),
    ("cake",             DEFAULT_USE, ["minecraft:cake"],                   False),
    ("campfire",         ITEM_USE,    ["minecraft:campfire", "minecraft:soul_campfire"], False),
    ("cartography_table", DEFAULT_USE, ["minecraft:cartography_table"],     True),
    ("cauldron",         ITEM_USE,    "#minecraft:cauldrons",               False),
    ("chest",            DEFAULT_USE, ["minecraft:chest"],                  True),
    ("crafting_table",   DEFAULT_USE, ["minecraft:crafting_table"],         True),
    ("dispenser",        DEFAULT_USE, ["minecraft:dispenser"],              True),
    ("dropper",          DEFAULT_USE, ["minecraft:dropper"],                True),
    ("ender_chest",      DEFAULT_USE, ["minecraft:ender_chest"],            True),
    ("flower_pot",       DEFAULT_USE, ["minecraft:flower_pot"],             False),
    ("furnace",          DEFAULT_USE, ["minecraft:furnace"],                True),
    ("grindstone",       DEFAULT_USE, ["minecraft:grindstone"],             True),
    ("hopper",           DEFAULT_USE, ["minecraft:hopper"],                 True),
    ("jukebox",          DEFAULT_USE, ["minecraft:jukebox"],                False),
    ("lectern",          DEFAULT_USE, ["minecraft:lectern"],                False),
    ("loom",             DEFAULT_USE, ["minecraft:loom"],                   True),
    ("note_block",       DEFAULT_USE, ["minecraft:note_block"],             False),
    ("shulker_box",      DEFAULT_USE, "#minecraft:shulker_boxes",           True),
    ("smithing_table",   DEFAULT_USE, ["minecraft:smithing_table"],         True),
    ("smoker",           DEFAULT_USE, ["minecraft:smoker"],                 True),
    ("stonecutter",      DEFAULT_USE, ["minecraft:stonecutter"],            True),
    ("trapped_chest",    DEFAULT_USE, ["minecraft:trapped_chest"],          True),
    ("vault",            ITEM_USE,    ["minecraft:vault"],                  False),
]


def write(path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def dump(obj):
    return json.dumps(obj, indent=2) + "\n"


def main():
    for name, trigger, blocks, gui in TABLE:
        advancement = {
            "criteria": {
                "use": {
                    "trigger": trigger,
                    "conditions": {
                        "location": {
                            "predicate": {"block": {"blocks": blocks}},
                            "type": "minecraft:location_check",
                        }
                    },
                }
            },
            "rewards": {"function": f"{NS}/block/{name}"},
        }
        write(ROOT / f"advancement/core/internal/pev/block/{name}.json", dump(advancement))

        write(
            ROOT / f"function/core/internal/pev/block/{name}.mcfunction",
            f"# macroengine:core/internal/pev/block/{name} (generated by tools/gen_block_events.py)\n"
            f"# Reward of the {name} advancement. @s = the player who used the block.\n"
            f"advancement revoke @s only {NS}/block/{name}\n"
            f"function #{NS}/block/{name}\n",
        )

        values = [f"#{NS}/block_use"] + ([f"#{NS}/open_gui"] if gui else [])
        write(ROOT / f"tags/function/core/internal/pev/block/{name}.json", dump({"values": values}))

    write(ROOT / "tags/function/core/internal/pev/block_use.json", dump({"values": []}))


if __name__ == "__main__":
    main()
