# guikit:gate/v5/load - load gate for guikit v5 (generated by the archive-gates patch)
# Returns 1 = pack may initialise, 0 = pack stays inert. Never blocks server startup.
# Gates: 0 archive notice | 1 version/format (+ variant conflict) | 2 operator confirm
#        3 lockdown | 4 reload breaker | 5 sink guard (inline in the macro-sink functions)

# Gate 0: archive notice (console + chat)
say [guikit] ARCHIVED datapack (vortacraftmc/core, 2026-10-03): unmaintained, deploy not recommended. It runs commands at server permission level and can lag, crash or alter your world - review the code and back up first. See ARCHIVED.md in the pack folder.

scoreboard objectives add guikit.gate dummy
execute unless data storage guikit:gate/v5 state run data modify storage guikit:gate/v5 state set value "pending"

# Gate 2: confirmation is bound to the pack version; a different version re-arms it.
# A locked pack stays locked until unlock.
execute unless data storage guikit:gate/v5 {confirmed:"v5"} run data modify storage guikit:gate/v5 state set value "pending"
execute if data storage guikit:gate/v5 {confirmed:"v5"} unless data storage guikit:gate/v5 {state:"locked"} run data modify storage guikit:gate/v5 state set value "active"

# Gate 4: reload breaker. More than 5 loads with gaps of 200 ticks or less -> lock.
scoreboard players add #last guikit.gate 0
scoreboard players add #n guikit.gate 0
execute store result score #now guikit.gate run time query gametime
scoreboard players operation #dt guikit.gate = #now guikit.gate
scoreboard players operation #dt guikit.gate -= #last guikit.gate
execute if score #dt guikit.gate matches 0..200 run scoreboard players add #n guikit.gate 1
execute unless score #dt guikit.gate matches 0..200 run scoreboard players set #n guikit.gate 1
scoreboard players operation #last guikit.gate = #now guikit.gate
execute if score #n guikit.gate matches 6.. run data modify storage guikit:gate/v5 state set value "locked"
execute if score #n guikit.gate matches 6.. run data modify storage guikit:gate/v5 reason set value "reload breaker: more than 5 loads within 200 ticks of each other"

# Result
execute if data storage guikit:gate/v5 {state:"active"} run return 1
execute if data storage guikit:gate/v5 {state:"locked"} run say [guikit] LOCKED. Reason is in storage guikit:gate/v5 (reason). Operator: tag yourself guikit.gate_admin, then run /function guikit:gate/v5/unlock
execute if data storage guikit:gate/v5 {state:"pending"} run say [guikit] PENDING operator confirmation - the pack is inert. 1) /tag <you> add guikit.gate_admin  2) /function guikit:gate/v5/confirm {format:122}  (format = data pack version of your server, pack_version.data in its version.json; this build targets 122)
return fail
